# ==========================================
# HashiCorp Vault Configuration
# ==========================================
spring.config.import=optional:vault://
spring.cloud.vault.uri=${VAULT_URI:http://localhost:8200}
spring.cloud.vault.token=${VAULT_TOKEN:root}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=notification-engine/common
spring.cloud.vault.kv.application-name=notification-engine/notificationservice
app.required-secrets=spring.datasource.username,spring.datasource.password

# ==========================================
# Dynamic Application Name and Port
# ==========================================
spring.application.name=notificationservice

# ==========================================
# SQL DB Connection Config
# ==========================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:notification_engine}?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:xxxxxxxxxxxxxxx}
spring.datasource.password=${DB_PASSWORD:xxxxxxxxxxxxxxx}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL:20}

# ==========================================
# Redis Cloud / Container Connection Config
# ==========================================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# Redis Cache Custom Configuration
app.cache.user.ttl-hours=${USER_CACHE_TTL_HOURS:24}

# ==========================================
# Kafka Producer Configuration
# ==========================================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
notification.kafka.topic.partitions=${KAFKA_PARTITIONS:10}

# ==========================================
# Confluent / Apache Kafka Cluster Config
# ==========================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}

# Sasl configuration placeholders Confluent Cloud authorization protocols ---- Only for future use case
# spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:PLAIN}
# spring.kafka.properties.sasl.jaas.config=${KAFKA_JAAS_CONFIG:}

# High Availability configurations
spring.kafka.properties.session.timeout.ms=${KAFKA_SESSION_TIMEOUT:45000}
spring.kafka.client-id=${KAFKA_CLIENT_ID:notificationservice-client}

# ==========================================
# Observability & Metrics
# ==========================================
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# ==========================================
# Loki Logging Connection
# ==========================================
loki.url=${LOKI_URL:http://localhost:3100/loki/api/v1/push}