global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'notification-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # Notification API
          - 'host.docker.internal:8081' # Processor
          - 'host.docker.internal:8090' # Email Consumer
          - 'host.docker.internal:8091' # SMS Consumer
          - 'host.docker.internal:8092' # Push Consumer
          - 'host.docker.internal:8093' # WhatsApp Consumer

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
